language: python
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35,coveralls
  - python: 3.5
    env: TOXENV=py35-devel
  - python: 3.4
    env: TOXENV=py34
  - python: 3.3
    env: TOXENV=py33
  - python: 2.7
    env: TOXENV=py27,coveralls
  - python: 2.7
    env: TOXENV=py27-devel
  - python: 2.6
    env: TOXENV=py26
install: pip install tox
script: tox
deploy:
  provider: pypi
  user: nickfrostatx
  password:
    secure: aup+2ktC4MlBVhxhIgxpBmawML2+1F2VqpMtfXKGBn0Muxu5vHwpqaMZ1scbN73UyaD7pGWmMsDdJ1SK3pcVtAUSH3Fd/Ure5bTnT1MgfnrM6wQseMmRx5x2G2ILUY/w39mjoSQWFRviT+0Uu0X1yaspIRRIlFNnGE6QL7VuKakhK1W1IyrR42lStAISsonbungWZiWLwmdYQsXBPPKVMSyawrpE1VUwbIZ6pQp5zVtwiUt+Ogvz5HC2/+Yd3sYwqCG/7U+hEnsjfonvy5kmYxZxeQsMrWW2xEwzr3Ouxox7LddsIrqh4fev7XEznvfsuS6oC3uktOmQPMN3BzUlWCGArep1puc32m8TQCeTCI5pab13Aez6mq5Jne3hhYhWKS1RRWpDgE8hMyw9iIV1sArJSlNiq6y0iuY9WUk3jfuGOAVd4eoA7jjKcbZrJCTTvyOAtb9zfja/HoVLNef9nQY5AGWByySjoBm/U1rwTtuftiwTm4r4pIiJu3vfw6asWSnmwxXQbfyxs6MTLYhSAxSzBHfRUnUeoCQVI6qCR7krT/DTgQOhVhz7bf9/36s3AEqO9vMxLKHuyasuiqZdLA95zBTDUrfGe1uMKl/bhvvQmzfL8Ywl1yi1BgoVd1hSdRshsfC3U0a23QUODXnWjCByzjuZQKEj130MPAMLBKE=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: $TRAVIS_JOB_NUMBER = *.1
